##############################CONFIG.YML##############################
motd:
  ingame-text: '&9Welcome to the &4server&f! '
  system-text: '&5DEFAULT&f-&cMOTD '
##############################CONFIG.YML##############################
